version: "3.7"

services:
  app:
    container_name: green-again-frontend
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
